### ISSUE TITLE
Requirements and getting it to work

### ISSUE THREAD

**Issue by w0rldart** [bgultekin/laravel-datatables-bundle#10]
Well, just installed the bundle and have been wondering on how to actually make it work.

```
$test = Article::select('title', 'id', 'subtitle');
$view = View::make('admin.templates.articles',
        array(
            'test' => Datatables::of($test)->make(),
        )
     );
$this->layout->content = $view;
```

And the output is only a json encoded string. Also trying loading `jquery.dataTables.min.js` and still get the same output

**Comment by Steenkuyl** [comment]
I have the same issue. Did you solve it?

**Comment by bgultekin** [comment]
I don't remember if eloquent supports non-array items in select as parameters. I mean this usage may not be true:
`Article::select('title', 'id', 'subtitle');`
Try this:
`Article::select(array('title', 'id', 'subtitle'));`

Also, It should give a json string. This bundle is not a complete datatables-php-javascript structure. It handles just server-side (php) by being careful about standart parameters of datatables jquery plugin. You should read about client side configuration of the plugin at its [website](http://datatables.net/).

**Comment by Steenkuyl** [comment]
Yes thanks, i did indeed needed to add the proper datatables jquery command. Works great
