### ISSUE TITLE
How to use SQL functions?

### ISSUE THREAD

**Issue by larsurilch** [bgultekin/laravel-datatables-bundle#12]
I need to concatenate values ​​of multiple columns. Something like http://forums.laravel.io/viewtopic.php?id=1527.
I made a few attempts but all without success.
Thanks

**Comment by bgultekin** [comment]
If I didn't misunderstand. You can do it like:

$items = Deal::select(array('id','name','surname','gender'));
Datatables::of($items)
 ->edit_column('name','{{ $name.' '.$surname }}')
 ->remove_column('surname')
 ->make();

Also you can use sql concat to do this, of course. If you share error, I can help more.

**Comment by larsurilch** [comment]
Hello bllim,

Thank you for your help. I managed to solve using edit_column.
