### ISSUE TITLE
Compatibilty with Laravel 4

### ISSUE THREAD

**Issue by andersholst** [bgultekin/laravel-datatables-bundle#13]
Have you considered updating your excellent bundle to a Laravel 4 compatible package?

**Comment by bgultekin** [comment]
Yes, I think  to update as soon as possible. Thanks for reminding :) .

**Comment by mackhankins** [comment]
I was just looking for this to use with L4.  I was going to make my own package if it didn't exist.

**Comment by bgultekin** [comment]
Finally, I found time to make this :). 

Github: https://github.com/bllim/laravel4-datatables-package
Packagist: https://packagist.org/packages/bllim/datatables

**Comment by mackhankins** [comment]
Thanks, this is working great for me.
