### ISSUE TITLE
Object with has_one?

### ISSUE THREAD

**Issue by Thijmen** [bgultekin/laravel-datatables-bundle#14]
Hi,

I want to grab the following:
$data = Hour::select(array('client.name', 'hour.id'));
Assuming that hour has_one client, how do I make the datatables?

**Comment by bgultekin** [comment]
You can use join like below:

```
$data = Hour::select(array('client.name', 'hour.id'))->join('client','client.hour_id','=','hour.id');
```

**Comment by Thijmen** [comment]
`$hours = Hour::select(array('projects.name', 'clients.name', 'hours.checkin', 'hours.checkout'))
                        ->join('projects', 'projects.id','=', 'hours.project_id')
                        ->join('clients','clients.id','=', 'projects.client_id');
        return Datatables::of($hours)->make();`

Clients.name is showing up in the json array, yet projects.name isnt :(

**Comment by Thijmen** [comment]
Perhaps I need to say that boh projects and clients have a colum named `name`, is this a big issue? I can view projects.description

**Comment by Thijmen** [comment]
I fixed it by replacing 'projects.name' to  'projects.name AS projectname' in my selectquery. I think you should document this somewhere :)

**Comment by Thijmen** [comment]
Too bad, when I want to order a colomn, it throws a mysql error;
`ORDER BY`projects`.`name`AS`test`

**Comment by bgultekin** [comment]
As you said, probably it is related to same column name. You can rename them in select by using "as".

```
$hours = Hour::select(array('projects.name as projectname', 'clients.name as clientname', 'hours.checkin', 'hours.checkout'))
->join('projects', 'projects.id','=', 'hours.project_id')
->join('clients','clients.id','=', 'projects.client_id');
return Datatables::of($hours)->make();
```

**Comment by Thijmen** [comment]
That won't work with ordering. Is it possible to fix without altering the table?

**Comment by bgultekin** [comment]
Can you give lines which you try to order on it?

**Comment by Thijmen** [comment]
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'AS `test` ASC LIMIT 10 OFFSET 0' at line 1

`SQL: SELECT `projects`.`description`, `projects`.`name` AS `test`, `clients`.`name`, `hours`.`checkin`, `hours`.`checkout` FROM `hours` INNER JOIN `projects` ON `projects`.`id` = `hours`.`project_id` INNER JOIN `clients` ON `clients`.`id` = `projects`.`client_id` ORDER BY `projects`.`name` AS `test` ASC LIMIT 10 OFFSET 0`

**Comment by bgultekin** [comment]
Php eloquent part ?

**Comment by Thijmen** [comment]
`$hours = Hour::select(array('projects.description','projects.name AS test', 'clients.name', 'hours.checkin', 'hours.checkout'))
                        ->join('projects', 'projects.id','=', 'hours.project_id')
                        ->join('clients','clients.id','=', 'projects.client_id');
        return Datatables::of($hours)->make();`

**Comment by bgultekin** [comment]
where is order part?

**Comment by Thijmen** [comment]
I mean, when I try to order the table (click on column name in table html)

**Comment by bgultekin** [comment]
Hmm ok. Sorry for late understand :) .
Can you try lowercase "as" like below. There may be a problem. If it works, I  will update the code.

```
$hours = Hour::select(array('projects.description','projects.name as test', 'clients.name', 'hours.checkin', 'hours.checkout'))
->join('projects', 'projects.id','=', 'hours.project_id')
->join('clients','clients.id','=', 'projects.client_id');
return Datatables::of($hours)->make();
```

**Comment by Thijmen** [comment]
Hi,

No point, your suggestion worked like a charm!!
