### ISSUE TITLE
How to Get Total Data of Columns

### ISSUE THREAD

**Issue by deerawan** [bgultekin/laravel-datatables-bundle#21]
Hi Bilal, 

I have a table with debet and credit column and want to display the total of each those columns in the footer. Do you have any suggestion how to get this? 

The main challenge is because of AJAX. If the total rows is 100 and the total paginated rows is 15, the SUM is calculated for just 15 rows if we use fnFooterCallback. 
http://stackoverflow.com/questions/14563886/datatable-fnfootercallback-summing-columns

**Comment by bgultekin** [comment]
Nothing comes to mind. But you can do this seperately from this bundle. Just calculate sum and add it to footer of table. I think this is simplest way.
