### ISSUE TITLE
bug when we try to sort a column named like '%as%"

### ISSUE THREAD

**Issue by KelioDev** [bgultekin/laravel-datatables-bundle#3]
Hi,

Thanks for your great job. It's a very usefull bundle.

I think i found a bug.
If column name is like '%as%' , a click on header to order by this column cause a bug in json data.
It's because column name is troncated by :

$temp = explode('as', $this->columns[$i]);   row 225 of Datatables.php

I replace by 
$temp = explode(' as ', $this->columns[$i]);

And now eveything is working.

Kelio

**Comment by bgultekin** [comment]
Thanks, for finding bug and fixing. I commit it.
