### ISSUE TITLE
Unable to search with unicode characters

### ISSUE THREAD

**Issue by awsp** [bgultekin/laravel-datatables-bundle#4]
I have been tearing out my hair try to figure out the search in laravel datatables for couple days. 

I got no problems when typing in english characters such as alphabetic or numeric characters and the correct results come out. 

But when I try to type Japanese characters, I started to get the following error. 
`DataTables warning (table id = 'DataTables_Table_0'): DataTables warning: JSON data from server could not be parsed. This is caused by a JSON formatting error.`

I know this message is from the jQuery plugin datatable but from what I have traced, it turns out that JSON object was emptied. 

I then went the `:bundle/datatables/DataTables.php` , paste some debug code and observe the check points I passed, and I found that the executions ended at the following line whenever I type non-English characters, 

`public function make() { ... }`
`private function get_result() { ... }`
`$this->result_object = $this->query->get(); (Around line: 72)`

So instead of having the default `Input::get('sSearch')` in DataTables.php, I hardcoded an extra search option into my Eloquent Object before calling make(), something like, 
`$sSearch = 'テキスト' // Japanese Characters;`
`Book::where( 'name', 'LIKE', '%' . $sSearch . '%')->order_by('created_at', 'desc');`

It does work in this case (Without getting input from end-user). 
I suspect that this has to do with some sort of encoding problem. 
But my unit test show that the Input::get('sSearch') of what I entered as end-user is `===` totally equal to the hardcoded one. And I am back to the beginning that I don't know why it just doesn't work on non-English characters. 

Sorry for my bad explanation. Any comments / advices are welcomed.

**Comment by bgultekin** [comment]
Hi, sorry for delayed response.

I tested with japanese character. I got these error which is (i guess) related to mysql: 

```
General error: 1271 Illegal mix of collations for operation 'like'

SQL: SELECT `pages`.`id`, `pages`.`name`, `pages`.`name_slug`, `pages`.`created_at`, `vf_users`.`username`, `pages`.`status` FROM `pages` LEFT JOIN `vf_users` ON `pages`.`vf_user_id` = `vf_users`.`id` WHERE (`pages`.`id` LIKE ? OR `pages`.`name` LIKE ? OR `pages`.`name_slug` LIKE ? OR `pages`.`created_at` LIKE ? OR `vf_users`.`username` LIKE ?) ORDER BY `pages`.`created_at` DESC LIMIT 10 OFFSET 0

Bindings: array (
  0 => '%テキスト%',
  1 => '%テキスト%',
  2 => '%テキスト%',
  3 => '%テキスト%',
  4 => '%テキスト%',
)
```

What is your exact error? You can observe by using developer tools in chrome (network tab). As another way, you can reach your json page with these parameters to see error:

```
page.php??sEcho=4&iColumns=5&sColumns=&iDisplayStart=0&iDisplayLength=10&mDataProp_0=0&mDataProp_1=1&mDataProp_2=2&mDataProp_3=3&mDataProp_4=4&sSearch=テキスト&bRegex=false&sSearch_0=&bRegex_0=false&bSearchable_0=true&sSearch_1=&bRegex_1=false&bSearchable_1=true&sSearch_2=&bRegex_2=false&bSearchable_2=true&sSearch_3=&bRegex_3=false&bSearchable_3=true&sSearch_4=&bRegex_4=false&bSearchable_4=true&iSortCol_0=1&sSortDir_0=desc&iSortingCols=1&bSortable_0=true&bSortable_1=true&bSortable_2=true&bSortable_3=true&bSortable_4=true&_=1352315732686
```

Lastly, it is weird that it works with japanese characters at normal usage as you specified. But I review datatables code and I really couldn't see anything can cause this error. 

It will be helpful to see your error. 
Thanks for your interest.

**Comment by awsp** [comment]
I think I know why this is happening and yes, this looks like a MySQL problem. 
I was unable to print out the SQL since PHP stop executing before it is "recorded" to `DB::profile()`
I actually found that query is not listed in `DB::profile()`

Okay, anyway. I was actually filtering a `datetime` field  and MySQL complaints about it. 
So I went disable that column via `aoColumns` from the datatables init script it is now working. 
Thank you very much for helping me w/ this issue.  

> Just some of my thoughts

Just recently switch to Laravel from a CodeIgniter base and I love to use Laravel for my next major project. 
Overall, this is a really great bundle and saved me a lots of time reimplementing the script. 

To be honest, I was struggling with my custom columns before using this bundle and I really like the feature, `add_column()`, `edit_column()` and `remove_column()`. Good Job! 

> Something else unrelated. 

I notice at line 351, what exactly does it do? 
  `$first_time = false;`

According to [PHPBench](http://www.phpbench.com/), 
Instead of 
  `for ($i=0;$i<count($this->columns);$i++) { ... }`
Having this might boost up the performance a bit when having lots of column to filter. 
  `for ($i=0,$c=count($this->columns);$i<$c;$i++) { ... }`

**Comment by bgultekin** [comment]
Thanks for your cooperation.

Line 351 is a trash. Sorry for that, probably it is coming from under released version. I am deleting it.
About usage of for loop, you are right, I will fix it.

**Comment by awsp** [comment]
Thanks for the update. 
Just re-check out the newer version. 
I think there is one typo so the script is not working. 

At line 360
instead of 
    `for ($i=0,$c<count($this->columns);$i<$c;$i++)`
It should be 
    `for ($i=0,$c=count($this->columns);$i<$c;$i++)`

**Comment by bgultekin** [comment]
Sorry for mistaking, I fixed and tried it. Now, it seems okay.

**Comment by summerblue** [comment]
For who is reading this :+1:

```
var oTable;
$(document).ready(function() {
    oTable = $('#features').dataTable( {
        "sDom": "<'row'<'col-md-6'l><'col-md-6'f>r>t<'row'<'col-md-6'i><'col-md-6'p>>",
        "sPaginationType": "bootstrap",
        "oLanguage": {
            "sLengthMenu": "_MENU_ 每页显示数量"
        },

        // this is for search column, specify witch is searchable
        // in my case I have four colum: id, title, description, created_at
        "aoColumns": [
            {"bSearchable": false },
            {"bSearchable": true },
            {"bSearchable": true },
            {"bSearchable":false},
        ],

        "bProcessing": true,
        "bServerSide": true,
        "sAjaxSource": "{{ URL::to('admin/features/data') }}",
        "fnDrawCallback": function ( oSettings ) {
            $(".iframe").colorbox({iframe:true, width:"80%", height:"80%"});
        }
    });
});
```
